image: python:latest

before_script:
    - python --version
    - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt

build:
    stage: build
    script:
    - python main.py
    - echo "__pycache__" > .gitignore

after_script:
    - mkdir ~/.ssh/
    - ssh-keyscan $CI_SERVER_HOST > ~/.ssh/known_hosts
    - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - git remote remove ssh_origin || true
    - git remote add ssh_origin "git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git"
    - echo "git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git"
    - git config --global user.name "gitlab-bot"
    - git config --global user.email "bot@noreply.${CI_SERVER_HOST}"
    - git add .
    - git commit -m "Add sync changes"
    - git push -uf ssh_origin release